version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - .:/web
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - .:/web
        command: ["npm", "run", "test"]